export const marqueeImages = [
  "/images/marquee (1).jpeg",
  "/images/marquee (2).jpeg",
  "/images/marquee (3).jpeg",
  "/images/marquee (4).jpeg",
  "/images/marquee (5).jpeg",
];

export const sampleNfts: sampleNft[] = [
  {
    id: 1,
    name: "Haze #5773",
    src: "/images/nft (1).jpeg",
    price: "0.5 ETH",
    bid: "2.0 ETH",
    ends: "2h 55m 32s",
  },
  {
    id: 2,
    name: "Haze #342",
    src: "/images/nft (2).jpeg",
    price: "0.1 ETH",
    bid: "1.3 MATIC",
    ends: "2h 55m 32s",
  },
  {
    id: 3,
    name: "Haze #6542",
    src: "/images/nft (3).jpeg",
    price: "3.2 ETH",
    bid: "3.0 AVAX",
    ends: "2h 55m 32s",
  },
  {
    id: 4,
    name: "Haze #2342",
    src: "/images/nft (4).jpeg",
    price: "0.7 ETH",
    bid: "1.6 ETH",
    ends: "2h 55m 32s",
  },
  {
    id: 5,
    name: "Haze #675",
    src: "/images/nft (5).jpeg",
    price: "1.2 ETH",
    bid: "2.5 ETH",
    ends: "2h 55m 32s",
  },
  {
    id: 6,
    name: "Haze #2353",
    src: "/images/nft (6).jpeg",
    price: "2.0 ETH",
    bid: "4.2 ETH",
    ends: "2h 55m 32s",
  },
  {
    id: 7,
    name: "Haze #886",
    src: "/images/nft (7).jpeg",
    price: "1.1 ETH",
    bid: "5.4 ETH",
    ends: "2h 55m 32s",
  },
  {
    id: 8,
    name: "Haze #8972",
    src: "/images/nft (8).jpeg",
    price: "3.1 ETH",
    bid: "2.3 ETH",
    ends: "2h 55m 32s",
  },
];
