export const categories = [
  { id: 1, label: "All" },
  { id: 2, label: "Art" },
  { id: 3, label: "Gaming" },
  { id: 4, label: "Photography" },
];

export const marqueeImages = [
  "/images/marquee (1).webp",
  "/images/marquee (2).webp",
  "/images/marquee (3).webp",
  "/images/marquee (4).webp",
  "/images/marquee (5).webp",
];

export const sampleNfts: sampleNft[] = [
  {
    id: 1,
    name: "CryptoGlimmer #217",
    src: "/images/nft (1).webp",
    price: "0.5 ETH",
    bid: "2.0 ETH",
    ends: "2h 55m 32s",
    owner: "Haze",
    collection: "Galactic Echoes",
  },
  {
    id: 2,
    name: "DigitalEclipse #045",
    src: "/images/nft (2).webp",
    price: "0.1 ETH",
    bid: "1.3 MATIC",
    ends: "2h 55m 32s",
    owner: "Haze",
    collection: "Neon Dreamscapes",
  },
  {
    id: 3,
    name: "NeonOdyssey #388",
    src: "/images/nft (3).webp",
    price: "3.2 ETH",
    bid: "3.0 AVAX",
    ends: "2h 55m 32s",
    owner: "Haze",
    collection: "Ethereal Artifacts",
  },
  {
    id: 4,
    name: "PixelVoyage #029",
    src: "/images/nft (4).webp",
    price: "0.7 ETH",
    bid: "1.6 ETH",
    ends: "2h 55m 32s",
    owner: "Haze",
    collection: "Pixelated Paradigms",
  },
  {
    id: 5,
    name: "GalacticDreamer #174",
    src: "/images/nft (5).webp",
    price: "1.2 ETH",
    bid: "2.5 ETH",
    ends: "2h 55m 32s",
    owner: "Haze",
    collection: "Cyber Mythos",
  },
  {
    id: 6,
    name: "EtherealWanderer #909",
    src: "/images/nft (6).webp",
    price: "2.0 ETH",
    bid: "4.2 ETH",
    ends: "2h 55m 32s",
    owner: "Haze",
    collection: "Mystic Realms",
  },
  {
    id: 7,
    name: "CyberPhoenixRising #561",
    src: "/images/nft (7).webp",
    price: "1.1 ETH",
    bid: "5.4 ETH",
    ends: "2h 55m 32s",
    owner: "Haze",
    collection: "Quantum Odyssey",
  },
  {
    id: 8,
    name: "MysticRealmExplorer #202",
    src: "/images/nft (8).webp",
    price: "3.1 ETH",
    bid: "2.3 ETH",
    ends: "2h 55m 32s",
    owner: "Haze",
    collection: "Aurora Chronicles",
  },
];

export const collections = [
  {
    id: 1,
    name: "Galactic Echoes",
    by: "Hazee",
    volume: "4542 ETH",
    floor: "0.06 ETH",
    src: [
      "/images/collection-img (1).webp",
      "/images/collection-cover (1).gif",
      "/images/collection-cover (1).webp",
      "/images/collection-cover (2).webp",
    ],
  },
  {
    id: 2,
    name: "Neon Dreamscapes",
    by: "Hazee",
    volume: "2342 ETH",
    floor: "0.06 ETH",
    src: [
      "/images/collection-img (2).webp",
      "/images/collection-cover (3).webp",
      "/images/collection-cover (4).webp",
      "/images/collection-cover (5).webp",
    ],
  },
  {
    id: 3,
    name: "Ethereal Artifacts",
    by: "Hazee",
    volume: "1342 ETH",
    floor: "0.06 ETH",
    src: [
      "/images/collection-img (3).webp",
      "/images/collection-cover (6).webp",
      "/images/collection-cover (7).webp",
      "/images/collection-cover (8).webp",
    ],
  },
  {
    id: 4,
    name: "Hazee Art Wave",
    by: "Hazee",
    volume: "6342 ETH",
    floor: "0.06 ETH",
    src: [
      "/images/collection-img (4).webp",
      "/images/collection-cover (9).webp",
      "/images/collection-cover (10).webp",
      "/images/collection-cover (11).webp",
    ],
  },
  {
    id: 5,
    name: "Pixelated Paradigms",
    by: "Hazee",
    volume: "7342 ETH",
    floor: "0.06 ETH",
    src: [
      "/images/collection-img (5).webp",
      "/images/collection-cover (12).webp",
      "/images/collection-cover (13).webp",
      "/images/collection-cover (14).webp",
    ],
  },
  {
    id: 6,
    name: "Cyber Mythos",
    by: "Hazee",
    volume: "8342 ETH",
    floor: "0.06 ETH",
    src: [
      "/images/collection-img (6).webp",
      "/images/collection-cover (15).webp",
      "/images/collection-cover (16).webp",
      "/images/collection-cover (17).webp",
    ],
  },
  {
    id: 7,
    name: "Mystic Realms",
    by: "Hazee",
    volume: "9342 ETH",
    floor: "0.1 ETH",
    src: [
      "/images/collection-img (7).webp",
      "/images/collection-cover (18).webp",
      "/images/collection-cover (19).webp",
      "/images/collection-cover (20).webp",
    ],
  },
  {
    id: 8,
    name: "Quantum Odyssey",
    by: "Hazee",
    volume: "1442 ETH",
    floor: "0.16 ETH",
    src: [
      "/images/collection-img (8).webp",
      "/images/collection-cover (21).webp",
      "/images/collection-cover (22).webp",
      "/images/collection-cover (23).webp",
    ],
  },
];

export const creators = [
  {
    id: 1,
    username: "Figoti",
    name: "Figoti Mano",
    src: "/images/nft (5).webp",
    owns: 29,
    sold: 31,
    created: 45,
    cover: "/images/creator-cover (1).webp",
  },
  {
    id: 2,
    username: "Jake",
    name: "Jake Funes",
    src: "/images/nft (6).webp",
    owns: 6,
    sold: 29,
    created: 50,
    cover: "/images/creator-cover (1).webp",
  },
  {
    id: 3,
    username: "Ebuka",
    name: "Ebuka Okafor",
    src: "/images/nft (7).webp",
    owns: 12,
    sold: 52,
    created: 77,
    cover: "/images/creator-cover (2).gif",
  },
  {
    id: 4,
    username: "Michael",
    name: "Michael Init",
    src: "/images/nft (8).webp",
    owns: 19,
    sold: 44,
    created: 68,
    cover: "/images/creator-cover (3).gif",
  },
];
